# AndroidX and Jetifier enablement
android.useAndroidX=true
android.enableJetifier=true

# Kotlin Native ignore disabled targets
kotlin.native.ignoreDisabledTargets=true

# Default JVM target for Kotlin
kotlin.jvm.target.validationMode=warning

# Suppress SDK warning
android.suppressUnsupportedCompileSdk=34
