name: Android APK CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant Execute Permission to Gradlew
      run: chmod +x gradlew

    - name: Build Android APKs
      run: ./gradlew :android-sample:assembleDebug :android-sample:assembleRelease

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: android-sample-debug
        path: android-sample/build/outputs/apk/debug/android-sample-debug.apk

    - name: Upload Release APK (Unsigned)
      uses: actions/upload-artifact@v4
      with:
        name: android-sample-release
        path: android-sample/build/outputs/apk/release/android-sample-release-unsigned.apk

    - name: Create Global Release
      uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/master'
      with:
        tag_name: latest
        name: Latest Build
        draft: false
        prerelease: false
        files: |
          android-sample/build/outputs/apk/debug/android-sample-debug.apk
          android-sample/build/outputs/apk/release/android-sample-release-unsigned.apk
        generate_release_notes: true
        allow_updates: true
